---
name: Build and Run Tests

on:
  push:
    branches-ignore: [main]
    tags:
      - "**"
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-2022
          - macos-12
          - ubuntu-20.04

        build_type:
          - Debug
          - Release

        shared:
          - "True"
          - "False"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Checkout profiles
        uses: actions/checkout@v3
        with:
          repository: conan-burrito/profiles
          path: profiles

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install conan

      - name: Configure conan
        run: |
          conan --version
          conan profile detect
          conan config install ./profiles
          conan remote add conan-burrito "${{ secrets.CONAN_UPLOAD }}"
          conan remote login conan-burrito "${{ secrets.CONAN_LOGIN_USERNAME }}" -p "${{ secrets.CONAN_PASSWORD }}"

      - name: Build native
        run:  |
          conan create --user=conan-burrito --channel=stable -b missing -s compiler.cppstd=17 -s build_type=${{ matrix.build_type }} -o shared=${{ matrix.shared }} .

      - name: Upload artefacts
        run: conan upload -c -r conan-burrito sqlite-burrito/*

