---
name: Build and Run Tests on PRs

on:
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-2022
          - macos-12
          - ubuntu-20.04

        build_type:
          - Debug
          - Release

        shared:
          - ON
          - OFF

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Checkout profiles
        uses: actions/checkout@v3
        with:
          repository: conan-burrito/profiles
          path: profiles

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install conan

      - name: Configure conan
        run: |
          conan --version
          conan profile detect

      - name: Install dependencies
        run:  |
          conan install -b missing -s compiler.cppstd=17 -s build_type=${{ matrix.build_type }}  -c:h tools.cmake.cmake_layout:build_folder_vars='[]' .

      - name: Build library
        run:  |
          cmake -H. -Bbuild/${{ matrix.build_type }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON \
                -DCMAKE_TOOLCHAIN_FILE=./build/${{ matrix.build_type }}/generators/conan_toolchain.cmake  \
                -DBUILD_SHARED_LIBS="${{ matrix.shared }}"
          cmake --build build/${{ matrix.build_type }}

      - name: Run Tests
        run:  |
          ctest --test-dir build/${{ matrix.build_type }}
